import { FormEvent, useEffect, useMemo, useState } from 'react';
import {
  ApiError,
  JobStatusResponse,
  TargetFormat,
  createJob,
  getJob,
  targetFormats,
} from './api';

const apiKeyStorageKey = 'octoconv.apiKey';
const pollIntervalMs = 1800;

function describeError(error: unknown): string {
  if (error instanceof ApiError) {
    switch (error.status) {
      case 401:
        return 'API key is missing, invalid, or revoked.';
      case 413:
        return 'The selected file exceeds the upload size limit.';
      case 422:
        return error.message || 'This source/target conversion is not supported.';
      case 429:
        return 'Too many requests. Please wait and try again.';
      default:
        return error.message || `Request failed with status ${error.status}.`;
    }
  }

  if (error instanceof Error) {
    return error.message;
  }

  return 'Unexpected error.';
}

export default function App() {
  const [apiKey, setApiKey] = useState(() => localStorage.getItem(apiKeyStorageKey) ?? '');
  const [rememberApiKey, setRememberApiKey] = useState(() =>
    Boolean(localStorage.getItem(apiKeyStorageKey)),
  );
  const [file, setFile] = useState<File | null>(null);
  const [target, setTarget] = useState<TargetFormat>('webp');
  const [job, setJob] = useState<JobStatusResponse | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const canSubmit = useMemo(
    () => apiKey.trim().length > 0 && file !== null && !isSubmitting,
    [apiKey, file, isSubmitting],
  );

  useEffect(() => {
    if (rememberApiKey && apiKey.trim()) {
      localStorage.setItem(apiKeyStorageKey, apiKey.trim());
      return;
    }

    localStorage.removeItem(apiKeyStorageKey);
  }, [apiKey, rememberApiKey]);

  useEffect(() => {
    if (!job || job.status === 'done' || job.status === 'failed') {
      return undefined;
    }

    let cancelled = false;
    const timer = window.setInterval(async () => {
      try {
        const nextJob = await getJob({ apiKey: apiKey.trim(), jobId: job.job_id });
        if (!cancelled) {
          setJob(nextJob);
          setError(null);
        }
      } catch (pollError) {
        if (!cancelled) {
          setError(describeError(pollError));
        }
      }
    }, pollIntervalMs);

    return () => {
      cancelled = true;
      window.clearInterval(timer);
    };
  }, [apiKey, job]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!file) {
      setError('Choose a file to convert.');
      return;
    }

    setIsSubmitting(true);
    setError(null);
    setJob(null);

    try {
      const createdJob = await createJob({ apiKey: apiKey.trim(), file, target });
      setJob(createdJob);
    } catch (submitError) {
      setError(describeError(submitError));
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <main className="shell">
      <section className="hero" aria-labelledby="page-title">
        <p className="eyebrow">OctoConv</p>
        <h1 id="page-title">Convert files through the REST API</h1>
        <p className="lede">
          Upload an image, choose the target format, and download the converted file when the worker
          finishes processing it.
        </p>
      </section>

      <section className="card" aria-label="Upload form">
        <form onSubmit={handleSubmit} className="form">
          <label className="field">
            <span>API key</span>
            <input
              type="password"
              value={apiKey}
              placeholder="ApiKey value generated by manage-clients"
              autoComplete="off"
              onChange={(event) => setApiKey(event.target.value)}
            />
          </label>

          <label className="checkbox">
            <input
              type="checkbox"
              checked={rememberApiKey}
              onChange={(event) => setRememberApiKey(event.target.checked)}
            />
            <span>Remember this key in this browser</span>
          </label>

          <div className="grid">
            <label className="field">
              <span>File</span>
              <input
                type="file"
                accept=".png,.jpg,.jpeg,.webp,.heic,.tif,.tiff,image/*"
                onChange={(event) => setFile(event.target.files?.[0] ?? null)}
              />
            </label>

            <label className="field">
              <span>Target format</span>
              <select
                value={target}
                onChange={(event) => setTarget(event.target.value as TargetFormat)}
              >
                {targetFormats.map((format) => (
                  <option key={format} value={format}>
                    {format.toUpperCase()}
                  </option>
                ))}
              </select>
            </label>
          </div>

          <button type="submit" disabled={!canSubmit}>
            {isSubmitting ? 'Uploading…' : 'Convert'}
          </button>
        </form>
      </section>

      {(job || error) && (
        <section className="card result" aria-live="polite">
          {job && (
            <>
              <div className="result-row">
                <span>Job ID</span>
                <code>{job.job_id}</code>
              </div>
              <div className="result-row">
                <span>Status</span>
                <strong className={`status status-${job.status}`}>{job.status}</strong>
              </div>
              {job.download_url && (
                <a className="download" href={job.download_url} rel="noreferrer">
                  Download converted file
                </a>
              )}
              {job.status === 'failed' && (
                <p className="error">
                  {job.error_message || job.error_code || 'Conversion failed.'}
                </p>
              )}
            </>
          )}
          {error && <p className="error">{error}</p>}
        </section>
      )}
    </main>
  );
}
